const data = [
  {
    id: 1,
    name: "Agra",
    info: "Agra is a historic city in northern India, located on the banks of the Yamuna River. It is renowned worldwide for the iconic Taj Mahal, a UNESCO World Heritage site and a symbol of eternal love. Agra also features other Mughal architectural marvels such as Agra Fort and Fatehpur Sikri. The city offers rich cultural experiences, bustling markets, and traditional handicrafts like marble inlay work.",
    image: "/images/Agra.png",
    price: "35,758",
  },
  {
    id: 2,
    name: "Jaipur",
    info: "Jaipur, known as the 'Pink City', is the capital of Rajasthan and a major tourist destination. Famous for its majestic forts like Amber Fort and Nahargarh, and the City Palace, Jaipur showcases royal heritage and Rajput architecture. The city is also known for colorful bazaars selling gemstones, textiles, and handicrafts, as well as its traditional cuisine and cultural festivals.",
    image: "/images/Jaipur.png",
    price: "82,560",
  },
  {
    id: 3,
    name: "Goa",
    info: "Goa is a coastal paradise on the western coast of India, known for its sun-kissed beaches, vibrant nightlife, and Portuguese heritage. The region is famous for water sports, beach parties, and colonial-era churches such as Basilica of Bom Jesus. Goa also offers scenic villages, spice plantations, and a rich culinary culture blending Indian and Portuguese flavors.",
    image: "/images/Goa.png",
    price: "58,240",
  },
  {
    id: 4,
    name: "Delhi",
    info: "Delhi, the capital of India, is a bustling metropolis that seamlessly blends history with modernity. It is home to iconic landmarks such as the Red Fort, India Gate, Qutub Minar, and Humayun’s Tomb. Delhi is also known for its vibrant street food, lively markets like Chandni Chowk, and a rich cultural scene including museums, art galleries, and traditional festivals.",
    image: "/images/Delhi.png",
    price: "49,999",
  },
  {
    id: 5,
    name: "Kerala",
    info: "Kerala, known as 'God's Own Country', is a serene state in southern India famous for its lush greenery, tranquil backwaters, and network of canals. Tourists can enjoy houseboat cruises, visit tea and spice plantations, and explore historic forts and temples. Kerala is also celebrated for its traditional art forms like Kathakali, Ayurveda wellness therapies, and unique festivals such as Onam.",
    image: "/images/Kerala.png",
    price: "90,850",
  },
  {
    id: 6,
    name: "Mumbai",
    info: "Mumbai, India's largest city, is the country's financial and entertainment hub. Known as the 'City of Dreams', it is home to Bollywood, vibrant street markets, and iconic landmarks like the Gateway of India and Marine Drive. Mumbai offers a diverse culinary scene, lively nightlife, cultural festivals, and a blend of colonial and modern architecture.",
    image: "/images/Mumbai.png",
    price: "72,350",
  },
  {
    id: 7,
    name: "Manali",
    info: "Manali is a picturesque hill station in Himachal Pradesh, nestled in the Beas River valley of the Himalayas. It is famous for adventure sports like paragliding, skiing, and trekking, as well as its snow-capped mountains, lush forests, and scenic valleys. Visitors can explore ancient temples, vibrant local markets, and the nearby Solang Valley and Rohtang Pass.",
    image: "/images/Manali.png",
    price: "55,640",
  },
  {
    id: 8,
    name: "Varanasi",
    info: "Varanasi, one of the world's oldest continuously inhabited cities, is a spiritual hub on the banks of the Ganges. Known for its ghats, ancient temples, and evening Ganga Aarti, the city attracts pilgrims from across India and the world. Varanasi also offers rich cultural experiences through classical music, traditional silk weaving, and vibrant festivals like Diwali and Dev Deepawali.",
    image: "/images/Varanasi.png",
    price: "44,900",
  },
  {
    id: 9,
    name: "Udaipur",
    info: "Udaipur, the 'City of Lakes', is a romantic city in Rajasthan famous for its elegant palaces, scenic lakes, and historic havelis. Key attractions include the City Palace, Lake Pichola, and Jag Mandir. Udaipur also offers cultural experiences through traditional dance, folk music, art galleries, and royal cuisine, making it a favorite for honeymooners and history enthusiasts.",
    image: "/images/Udaipur.png",
    price: "67,420",
  },
  {
    id: 10,
    name: "Rishikesh",
    info: "Rishikesh, located on the banks of the Ganges in Uttarakhand, is the global hub for yoga, meditation, and spiritual retreats. Known as the 'Yoga Capital of the World', it also offers adventure activities such as white-water rafting, trekking, and camping. The city is dotted with ashrams, suspension bridges like Laxman Jhula, and hosts festivals like International Yoga Festival.",
    image: "/images/Rishikesh.png",
    price: "39,870",
  },
  {
    id: 11,
    name: "Shimla",
    info: "Shimla, the capital of Himachal Pradesh, is a charming hill station known for its colonial architecture, cool climate, and scenic landscapes. Attractions include The Ridge, Mall Road, Jakhoo Temple, and Viceregal Lodge. Shimla offers adventure sports, nature walks, local handicrafts, and winter festivals, making it a year-round tourist destination.",
    image: "/images/Shimla.png",
    price: "53,480",
  },
  {
    id: 12,
    name: "Darjeeling",
    info: "Darjeeling, in West Bengal, is famous for its tea gardens, panoramic views of the Kanchenjunga, and the historic Darjeeling Himalayan Railway. The town offers a tranquil escape with monasteries, scenic hills, and botanical gardens. Visitors can enjoy local cuisine, explore Tibetan culture, and attend cultural events like the Darjeeling Carnival.",
    image: "/images/Darjeeling.png",
    price: "61,330",
  },
  {
    id: 13,
    name: "Leh-Ladakh",
    info: "Leh-Ladakh is a high-altitude region in northern India known for its stark landscapes, Buddhist monasteries, and adventure opportunities. Popular activities include trekking, river rafting, and motorbiking along the scenic mountain passes. The region is culturally rich, with festivals like Hemis, stunning lakes like Pangong and Tso Moriri, and opportunities to experience Tibetan and Ladakhi traditions.",
    image: "/images/Ladakh.png",
    price: "96,750",
  },
  {
    id: 14,
    name: "Andaman Islands",
    info: "The Andaman Islands, located in the Bay of Bengal, are famous for their pristine beaches, turquoise waters, and vibrant coral reefs. Activities include snorkeling, scuba diving, sea walking, and exploring tropical forests. The islands also offer historical sites like Cellular Jail, local tribal culture, seafood cuisine, and eco-tourism experiences.",
    image: "/images/Andaman.png",
    price: "1,12,340",
  },
  {
    id: 15,
    name: "Mysore",
    info: "Mysore, in Karnataka, is a city rich in cultural heritage and royal history. Famous for Mysore Palace, Chamundi Hill, and the annual Dussehra festival, the city also offers traditional silk sarees, sandalwood products, and Mysore Pak sweets. Visitors can enjoy yoga centers, historical temples, and the blend of colonial and Indian architecture.",
    image: "/images/Mysore.png",
    price: "46,780",
  },
];

export default data;